### ISSUE TITLE
Config Parser

### ISSUE THREAD

**Issue by Dustpancake** [Dustpancake/Asteroid#13]
At the moment the python code is relying on environment variables which is sets in the run.py etc.. At some point we'll need to change and use proper config files so we can ship and deploy for different environments easily.

**Comment by Moontemple** [comment]
Obviously the config parsing for python is straight forward - python can read from a local file and adjust its behaviour from variables. How are we planning to do this for JS, which is on the browser end and thus can't access files.

I can think of a few options: 

- Server adds and endpoint for a minimal config file, which the JS loads each time it is needed. Would need to validate that the browser is also following said config file. 

- Add a routine to the python startup which physically edits the JS files and hardcodes the desired behaviour using tags.

I'm leaning towards the second option, as it seems less browser intensive, and makes fewer GET requests to the python server. Since altering the python behaviour requires a restart, this wouldn't be much of a problem for changing the JS - i.e., no server, no JS to load.

However, if there's another method someone can think of, or if a library exists already that would help with this, link it here. I have done zero research into this - I am just chucking my ideas out there.

**Comment by Moontemple** [comment]
Also, the SCSS and CSS files need to be configured somehow. I don't know if SCSS provides us with the ability to do this? If it does, could the idiom be extended for JS?

**Comment by JrTheDragon01** [comment]
@Moontemple happy to work on some python to manually edit js files on startup. Wrt get requests - is it more intensive to make multiple requests for smaller files or one request for the same amount of stuff in one big file? If the former, I could also make the startup python condense all my various js libraries into one big file on a per-endpoint basis so that fewer gets are made for the JS; would also deprecate my ordered loading workaround cutting down on the number of lines that need to be loaded in.

**Comment by JrTheDragon01** [comment]
@Dustpancake have done all the necessary work for the JS part of this afaik - will remove myself from the list of assignees

**Comment by Dustpancake** [comment]
Skeleton config parser now in place with unit tests e2ec65bcbaf67f6dadca501745fa0de9653106ec.

**Comment by JrTheDragon01** [comment]
@Dustpancake what more needs to be done wrt this issue to close?

**Comment by Dustpancake** [comment]
The config parser at the moment has been implemented for all of the database paths (which was arguably the trickiest part, as the paths are required in multiple modules). 

What's still left is:

- make a call to the JS config parser (I need to discuss with you exactly what the `dict` parameter should contain)

- load the host and port values to their respective places

- allow command line flags to override some config aspects (helps for debugging)

**Comment by JrTheDragon01** [comment]
As of 126f1816f127829adbd57f58359f551f6e8a219b, port and host values are correctly loaded in and overridden by cmd line flags; as of 5c07bafbba4a6702720563502e168fe1b1ab2d76 javascript config is also properly executed. @Dustpancake does anything else need doing wrt this issue or can it be closed?

**Comment by JrTheDragon01** [comment]
@Dustpancake I showed u my commits pls reply

**Comment by Dustpancake** [comment]
I was going to keep this issue open until everything that can be configured is configurable. If you think we should close and reopen when it's more concrete, well as of my latest commits, I had to hack a fix for getting the database path to the SQLAlchemy engine, so I want to neaten that up too before I'd be happy closing this issue for now.

**Comment by JrTheDragon01** [comment]
Alright sounds good, if you're fine doing that then we could close for now?

**Comment by Dustpancake** [comment]
Yeah sure, I mean it's technically not an issue anyway, just a bit of lazy coding. 

I'll close for now! :)
